import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import C_menuComponent from './componentes/c_menu.component'
import DEstilosEjemplo from './componentes/DEstilosEjemplo'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <C_menuComponent/>
        {children}
        <DEstilosEjemplo/>
        <footer>Footer</footer>
      </body>
    </html>
  )
}
